apiVersion: v1
kind: Secret
metadata:
  name: {{ include "travel-site.fullname" . }}-secret
  labels:
    {{- include "travel-site.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
