{{- if .Values.podDisruptionBudget.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}-backend-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: backend
    component: backend-pdb
spec:
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: backend
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.backend.unhealthyPodEvictionPolicy }}
{{- end }}