{{- if .Values.podDisruptionBudget.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}-frontend-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: frontend
spec:
  {{- if .Values.podDisruptionBudget.frontend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.frontend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.frontend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      component: frontend
  unhealthyPodEvictionPolicy: IfHealthyBudget
{{- end }}